### ISSUE TITLE
New ID System for WBI

### ISSUE THREAD

**Issue by jeljaik** [jeljaik/WB-Team-Issues#12]
Subtasks : 
- [x] https://github.com/jeljaik/WB-Team-Issues/issues/13 @jeljaik 
- [x] https://github.com/jeljaik/WB-Team-Issues/issues/22 @naveenoid 
- [x] port motorFrictionIdentification in codyco-modules @traversaro 
- [x] port torqueBalancing in codyco-modules @francesco-romano

**Comment by traversaro** [comment]
Ref issue: https://github.com/robotology/codyco-modules/issues/6

**Comment by traversaro** [comment]
.

**Comment by jeljaik** [comment]
As sort of documentation for (temporary) new joint/link/frame naming
ref. https://github.com/robotology/icub-main/issues/57

**Comment by traversaro** [comment]
This the porting of motorFriction modules, still need to be tested on the real robot.

**Comment by traversaro** [comment]
cc @francesco-romano this is the high priority!

**Comment by jeljaik** [comment]
@traversaro WBI-T Can be considered migrated now, with just a few improvement issues pending but not necessary for it to be used.

**Comment by traversaro** [comment]
Closed long time ago.
