### ISSUE TITLE
Modify mex-wholebodymodel to address world ref change, improving help

### ISSUE THREAD

**Issue by naveenoid** [jeljaik/WB-Team-Issues#23]
Copy of https://github.com/robotology-playground/mex-wholebodymodel/issues/7.

**Comment by jeljaik** [comment]
Do you think we can have this finished by Monday next week at most? We're gonna start the work in #19 with @luca-fiorio and we will need this feature soon enough. Sorry for the pressure :-(

**Comment by naveenoid** [comment]
Do-able. Will debug over the weekend. I wont be in on monday but will have
a tested version in the repos. Cheers and no pressure :)

---

Naveen Kuppuswamy, PhD
Post-doctoral Fellow,
Cognitive Humanoids Lab,
Department of Robotics, Brain and Cognitive Sciences (RBCS),
Istituto Italiano di Tecnologia, Genova, Italy

**Comment by naveenoid** [comment]
Addressed in Commit https://github.com/robotology-playground/mex-wholebodymodel/commit/2572fcb7937dd4bc6efc2ea0108f9f3def529ac3 . Needs some testing.

**Comment by naveenoid** [comment]
Leaving it open until Im confident of no bugs

**Comment by jeljaik** [comment]
ref https://github.com/robotology-playground/mex-wholebodymodel/issues/7
